sudo: false

language: node_js
node_js:
  - 9

branches:
  only:
    - master
deploy:
  provider: heroku
  app: "valdislav-react-app-test"
  api_key:
    secure: "f48f765f-7a12-4214-9a5d-ac23d8c01b58"
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js    